version: "3"

services:

  db:
    container_name: telegram_bot_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    container_name: telegram_bot_web
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./media/:/media
      - ./static/:/static
      - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    depends_on:
      - db

volumes:
  media:
  static:
  postgres_data: