# Generated by Django 3.2.7 on 2023-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='название проекта')),
                ('description', models.TextField(verbose_name='описание проекта')),
                ('image', models.ImageField(upload_to='images', verbose_name='картинка проекта')),
                ('is_aproved', models.BooleanField(default=False)),
            ],
        ),
    ]
